config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy ]
  resources :users, only: [:index, :show, :edit, :update ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: :true
  validates :body, presence: :true, length:{ maximum: 200 }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  def get_profile_image
    if profile_image.attached?
      profile_image
    else
      'no_image.jpg'
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    @user = current_user
    user_path(@user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    @users = User.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books =Book.all
      render :index
    end
  end


  def show
    @books = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
        render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:titl, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]

  def edit
    @user = User.find(params[:id])
    @book = Book.new
  end

  def index
    @users = User.all
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
  end

  def update
    @book = Book.new
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image , :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<%= flash[:notice] %>
<h2>user info</h2>
<div>
  <%= image_tag @user.get_profile_image%>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <% if @user.name != "guestuser" %>
    <div class='row'>
      <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
    </div>
  <% end %>

  <h2>New book</h2>
  <%= form_with model: Book, local:true do |f| %>
    <div class="form">
      <div class="text-field">
        <label for="book_title">Title</label>
      </div>
      <div class="text-field">
        <%= f.text_field :title, class:"form-control" %>
      </div>
    </div>
    <div class="form">
      <div class="text-field">
        <label for="book_opinion">Opinion</label>
      </div>
      <div class="text-field">
        <%= f.text_area :body, class:"form-control" %>
      </div>
    </div>
    <div class="form">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
div class="container">
  <!--エラー-->
  <div id="field-error">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-12">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title, class: "form-control" %>
        <h4>Opinion</h4>
        <%= f.text_area :body, class: "form-control" %>
        <%= f.submit 'Update Book',class: "btn btn-success" %>
　    <% end %>
      <%= link_to "Show",book_path(@book.id) %> | <%= link_to "Back",books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <!--エラー-->
  <div id="field-error">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <!--サイドバー-->
    <div class="col-md-3">
      <%= render 'books/list', book: @book %>
    </div>
    <!--一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <% @books.each do |books|%>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(books.user.id) do %>
                <%= image_tag books.user.get_profile_image %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(books.id) do %>
                <%= books.title %>
              <% end %>
            </td>
            <td>
              <%= books.body %>
            </td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <!--エラー-->
  <div id="field-error">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <!--サイドバー-->
    <div class="col-md-3">
      <%= render 'books/list', book: @book %>
    </div>
    <!--投稿詳細-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <% if @book.user.id == current_user.id %>
            <td>
              <%= link_to 'Edit', edit_book_path(@book.id), class: 'btn btn-sm btn-success' %>
            </td>
            <td>
              <%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？", class: 'btn btn-sm btn-danger' %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper mx-auto">
        <div class="row">
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
        </div>
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <!--ログイン中の表示-->
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fas fa-home" style="color: #ffffff;"></i>
                    Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users" style="color: #ffffff;"></i>
                    Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open" style="color: #ffffff;"></i>
                    Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt" style="color: #ffffff;"></i>
                    Log out
                  <% end %>
                </li>
              <% else %>
              <!--ログアウト後の表示-->
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home" style="color: #ffffff;"></i>
                    Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link" style="color: #ffffff;"></i>
                    About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus" style="color: #ffffff;"></i>
                    Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt" style="color: #ffffff;"></i>
                    Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <main>

    </main>
    <footer class="bg-none text-dark pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <!--エラー-->
  <div id="field-error">
    <% if @user.errors.any? %>
      <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-8">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <div class="field_with_errors">
            <label for="user_name">Name</label>
          </div>
          <div class="field_with_errors">
            <%= f.text_field :name, autofocus: true, class: "form-control name", id:"user_name" %>
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
            <label for="user_image">Image</label>
          </div>
          <div class="field_with_errors">
            <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*", class: "form-container-file user_image", id: "user_profile_image" %>
          </div>
        </div>
        <div class="form-group">
          <div class="field_with_errors">
            <label for="user_introduction">Introduction</label>
          </div>
          <div class="field_with_errors">
            <%= f.text_area :introduction, autofocus: true, class: "form-control introduction", id: "user_introduction" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <!--エラー-->
  <div id="field-error">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <!--サイドバー-->
    <div class="col-md-3 px-3">
      <%= render 'books/list', book: @book %>
    </div>
    <!--ユーザー一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </thead>
        <% @users.each do |users|%>
        <tbody>
          <tr>
            <td>
              <%= image_tag @user.get_profile_image%>
            </td>
            <td>
              <%= users.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(users.id) %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <!--エラー-->
  <div id="field-error">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row">
    <!--サイドバー-->
    <div class="col-md-3">
      <%= render 'books/list', book: @book %>
    </div>
    <!--投稿一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table">
          <thead>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </thead>
          <% @books.each do |books|%>
            <tbody>
              <tr>
                <td>
                  <%= link_to user_path(books.user.id) do %>
                    <%= image_tag books.user.get_profile_image %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(books.id) do %>
                    <%= books.title %>
                  <% end %>
                </td>
                <td>
                  <%= books.body %>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>